version: 7.1.5.{build}

branches:
  only:
    - develop
    - master
    - vnext

skip_tags: true

skip_commits:
  files:
    - docs/**/*
    - package.json
    - docs.yml
    - readme.md
    - .github/**/*

image:
  - Visual Studio 2019
  - Ubuntu

services:
  - mongodb
  - postgresql
  - mssql
  - rabbitmq
  - redis

build: off
test: off

artifacts:
  - path: artifacts/*.nupkg
    name: NuGet
  - path: artifacts/*.snupkg
    name: Symbols

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

# cmd and ps will only be ran on windows images, sh will only be ran on linux images
build_script:
  - cmd: >-
      SET PGUSER=postgres

      SET PGPASSWORD=Password12!

      PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%

      createdb MartenTest
  - ps: .\Build.ps1
  - sh: >-
      wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez

      sudo mkdir /usr/lib/rabbitmq/plugins

      sudo mv ./rabbitmq_delayed_message_exchange-3.8.0.ez /usr/lib/rabbitmq/plugins/

      sudo rabbitmqctl add_vhost test

      sudo rabbitmqctl set_permissions -p test guest ".*" ".*" ".*"

      sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange
  - sh: ./build.sh

install:
  # Follow Official Appveyor Initialization: https://github.com/appveyor-tests/CosmosDb/blob/master
  - ps: |
      Set-Content -Value '"C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" /NoUI /NoExplorer /NoFirewall' -Path .\startCosmosDb.cmd
      Start-Process -FilePath .\startCosmosDb.cmd
      .\waitforport.ps1 -port 8081 -maxAttempts 4

deploy:
- provider: NuGet
  name: PrePrerelease
  symbol_server: https://www.nuget.org
  artifact: NuGet, Symbols
  api_key:
    secure: rkQJpJebuP2jux5eZQLIiNSXs0NZmbC9s372eNosloj77PkdBQbLgMUYpzjn5lLE
  on:
    branch: vnext
- provider: NuGet
  name: Prerelease
  symbol_server: https://www.nuget.org
  artifact: NuGet, Symbols
  api_key:
    secure: rkQJpJebuP2jux5eZQLIiNSXs0NZmbC9s372eNosloj77PkdBQbLgMUYpzjn5lLE
  on:
    branch: develop
- provider: NuGet
  name: Release
  symbol_server: https://www.nuget.org
  artifact: NuGet, Symbols
  api_key:
    secure: rkQJpJebuP2jux5eZQLIiNSXs0NZmbC9s372eNosloj77PkdBQbLgMUYpzjn5lLE
  on:
    branch: master

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/27919bcbf1f770b0befd
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
