version: 6.1.0.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

skip_commits:
  files:
    - docs/**/*
    - package.json
    - docs.yml

image:
  - Visual Studio 2019
  - Ubuntu1804

services:
  - mongodb
  - postgresql
  - mssql
  - rabbitmq
  - redis

build: off
test: off

artifacts:
  - path: artifacts/*.*nupkg
    name: Packages

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

# cmd and ps will only be ran on windows images, sh will only be ran on linux images
build_script:
  - cmd: >-
      SET PGUSER=postgres

      SET PGPASSWORD=Password12!

      PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%

      createdb MartenTest
  - ps: .\Build.ps1
  - sh: >-
      wget https://dl.bintray.com/rabbitmq/community-plugins/3.6.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171215-3.6.x.zip

      sudo unzip ./rabbitmq_delayed_message_exchange-20171215-3.6.x.zip -d /usr/lib/rabbitmq/plugins

      sudo rabbitmqctl add_vhost test

      sudo rabbitmqctl set_permissions -p test guest ".*" ".*" ".*"

      sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange
  - sh: ./build.sh

install:
  # Follow Official Appveyor Initialization: https://github.com/appveyor-tests/CosmosDb/blob/master
  - ps: |
      Set-Content -Value '"C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" /NoUI /NoExplorer /NoFirewall' -Path .\startCosmosDb.cmd
      Start-Process -FilePath .\startCosmosDb.cmd
      .\waitforport.ps1 -port 8081 -maxAttempts 4

deploy:
- provider: NuGet
  name: Prerelease
  api_key:
    secure: IXB1AHgV9Bp8wic6oljIngn3e2gQuLZhpxa1yi8JpX1psFpKIDjYlyyDya01z56o
  on:
    branch: develop
- provider: NuGet
  name: Release
  api_key:
    secure: IXB1AHgV9Bp8wic6oljIngn3e2gQuLZhpxa1yi8JpX1psFpKIDjYlyyDya01z56o
  on:
    branch: master

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/27919bcbf1f770b0befd
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
